### ISSUE TITLE
Admin related info problems: display order and comprehensive results

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#111]
We are hoping the related info can display in chronological order with most recent first. Also, as emailed to Gabe on 8/4/15. It seems that when searching for related content, the system is not actually revealing the full content of the database.

For example. Let’s say I want to attach this Audio File https://wavefarm.org/admin/mr2bvg (name= Monday Musical Matinee: 20140120, Part 1) to this broadcast https://wavefarm.org/admin/kbajeq (name = 20150803)

I go into the broadcast page in admin https://wavefarm.org/admin/kbajeq, I type “Monday Musical Matinee” into the Audio field, but only 10 results display and none of the displayed are the one I am looking for. So I try to be even more specific, I type "Monday Musical Matinee: 20140120, Part 1” in the Audio field, but still no results!

**Comment by gsf** [comment]
The immediate issue here can be worked around by dropping the colon when typing in the related audio field ("monday musical matinee 20140120" returns the sought after file as a result), but it touches on two larger issues:
* #30, which should have addressed the problem of only seeing 10 hits in the completion dropdown, but I think missed that because I focused on the existing related items. With the latest commit there we now show up to 99 hits in the dropdown (I picked that number somewhat arbitrarily. It could be even higher but it will slow down things at some size.).
* wavefarm/api#60, which would make the completion smarter in a number of ways, including not choking on the colon. I made some progress there in the index but the search query in the admin needs to be modified and tested.

**Comment by galenjosephhunter** [comment]
Dropping the colon (and other punctuation marks) definitely helps, I'm not
seeing any sign of the increase (over 10) in the returned results though.
Am I missing something, or did that commit #30 not go through?


On Wed, Aug 5, 2015 at 9:26 PM, Gabriel Farrell <notifications@github.com>
wrote:

> The immediate issue here can be worked around by dropping the colon when
> typing in the related audio field ("monday musical matinee 20140120"
> returns the sought after file as a result), but it touches on two larger
> issues:
>
>    - #30 <https://github.com/wavefarm/admin/issues/30>, which should have
>    addressed the problem of only seeing 10 hits in the completion dropdown,
>    but I think missed that because I focused on the existing related items.
>    With the latest commit there we now show up to 99 hits in the dropdown (I
>    picked that number somewhat arbitrarily. It could be even higher but it
>    will slow down things at some size.).
>    - wavefarm/api#60 <https://github.com/wavefarm/api/issues/60>, which
>    would make the completion smarter in a number of ways, including not
>    choking on the colon. I made some progress there in the index but the
>    search query in the admin needs to be modified and tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/admin/issues/111#issuecomment-128200820>.
>



-- 


*Galen Joseph-Hunter**Executive Director*
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>

**Comment by gsf** [comment]
When you're in the "audio" related field and you type "monday", do you see a scrollbar on the side of the dropdown box?

**Comment by galenjosephhunter** [comment]
Now I do. I didn't before (I don't think.) So I think this is indeed
working as you described. Thank you!

On Sun, Aug 9, 2015 at 8:38 AM, Gabriel Farrell <notifications@github.com>
wrote:

> When you're in the "audio" related field and you type "monday", do you see
> a scrollbar on the side of the dropdown box?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/admin/issues/111#issuecomment-129177857>.
>



-- 


*Galen Joseph-Hunter**Executive Director*
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>
