### ISSUE TITLE
Search string to reveal all unpublished events

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#112]
The url I have given people to help them identify events added via “Add an Event” has just revealed itself to be problematic. I thought that this cleverly was a shortcut to help staff https://wavefarm.org/admin/?q=type%3Aevent%20_missing_%3Apublic&sort=timestamp

However, as we just discovered via some trial and error, an event added via the Website that is not public is not caught via the url above. If it is saved once without changing any info then it is. So there must be some condition of those website added events that makes the url above overlook them?

Is there anything we can do here so that a url can reveal unpublished content in admin for staff? This is a function that we had in the old site that very missed currently.

**Comment by gsf** [comment]
I'm not sure what changed -- I thought "_missing_:public" was the way to get these results as well! After some testing, however, I believe "public:false" now gets us there. So the full shortcut is as follows:
https://wavefarm.org/admin/?q=type%3Aevent+public%3Afalse&sort=-timestamp

A potential way to address these kinds of issues in the long term is #88.

**Comment by galenjosephhunter** [comment]
Updated shortcut appears to work. Thank you!

On Wed, Aug 5, 2015 at 10:12 PM, Gabriel Farrell <notifications@github.com>
wrote:

> I'm not sure what changed -- I thought "*missing*:public" was the way to
> get these results as well! After some testing, however, I believe
> "public:false" now gets us there. So the full shortcut is as follows:
> https://wavefarm.org/admin/?q=type%3Aevent+public%3Afalse&sort=-timestamp
>
> A potential way to address these kinds of issues in the long term is #88
> <https://github.com/wavefarm/admin/issues/88>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/admin/issues/112#issuecomment-128215233>.
>



-- 


*Galen Joseph-Hunter**Executive Director*
Wave Farm: Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405
518-622-2598 (o) | 917-297-1537 (c)
https://wavefarm.org/ <http://wavefarm.org/>
Sign-up for Wave Farm emails <http://eepurl.com/yRqVP>
