### ISSUE TITLE
admin.wavefarm.org "index"

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#21]
I believe there should be eight areas of content with which one can work when logged into admin.wavefarm.org
1. People (Artists, Hosts, Collaborators, On-air Guests)
2. Radio Shows
3. Broadcast Episodes Only
4. Broadcast Eposides + Calendar Events (people can physically attend)
5. Calendar Events Only
6. Works (Transmission Arts Archive Works)
7. Archive Files (Audio, Video, Images, Text)
*Playlist field to be added to archive file schema, possibly just retitle description field, "description + playlist"?
8. Newsroom

**Comment by gsf** [comment]
This addressed with ability to view types.
