### ISSUE TITLE
Related video, audio, text, image

### ISSUE THREAD

**Issue by gsf** [wavefarm/admin#54]
Can video, audio, text, image be added as possible related type of content to all admin pages: shows, works, events, broadcast, artists, audio, video, text, image, location?

**Comment by gsf** [comment]
A number of duplicates created for this one. Most closed.

**Comment by gsf** [comment]
@galenjosephhunter We want these relations on audio, image, text, and video? In the current/old admin archive files cannot be related to other archive files.

**Comment by galenjosephhunter** [comment]
Yes. The intent is for Archive Files to be related to one another in the new site, as this functionality has often been missed in the current/old admin.

**Comment by gsf** [comment]
Okay great I'll add that to the admin then.
