### ISSUE TITLE
Display dates for events in results

### ISSUE THREAD

**Issue by gsf** [wavefarm/admin#76]
See https://dev.wavefarm.org/admin/?q=WGXC+Community+Outreach+Advisory+Committee+Meeting

**Comment by gsf** [comment]
@galenjosephhunter thinking about this in the context of the related items widget, I think we're going to keep running into problems if each item is not distinguishable by its "main" field. In the case of events and broadcasts, that's the "name". Could we put a date or some other unique characteristic in the names of these items?

**Comment by galenjosephhunter** [comment]
Okay. I will pass those instructions on to staff.

On Sat, Apr 4, 2015 at 5:54 PM, Gabriel Farrell <notifications@github.com>
wrote:

> @galenjosephhunter <https://github.com/galenjosephhunter> thinking about
> this in the context of the related items widget, I think we're going to
> keep running into problems if each item is not distinguishable by its
> "main" field. In the case of events and broadcasts, that's the "name".
> Could we put a date or some other unique characteristic in the names of
> these items?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/admin/issues/76#issuecomment-89671219>.
>



-- 
*Galen Joseph-Hunter  /  **Executive Director  /  Wave Farm*
Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)

Subscribe to our email announcements: http://eepurl.com/yRqVP
(Wave Farm is incorporated as free103point9 Inc.)
