### ISSUE TITLE
Searching and selecting related items is difficult, if not impossible

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#82]
When I type in the name of something associated and click on it, it doesn't actually populate in the field.

Also, will there be an easier way to search, select, link associated info? Right now it appears one has to know the exact title/name of an item and type it in the field correctly for it to show up and be able to be selected.

**Comment by gsf** [comment]
Right now, typing any full word from the main field of an item should include it in the dropdown. Is that not the case?

In the future, the switch in #90 will improve the selection process. Do you have other ideas for improvement? For example, I just realized the ID should show the item as well (#91).

**Comment by galenjosephhunter** [comment]
Noted on #90 as well, but This would be very helpful. My instinct (as well as other's here) has been to click on the name to insert that info into the field. I've only figured out recently that it is hitting enter when the correct item is highlighted that works. Your suggestion here would be a huge help.

**Comment by gsf** [comment]
Clicking on the name should work as well. Sigh. Another regression. Coding too fast.

**Comment by gsf** [comment]
With the commit above clicking on the name should work again. Also, you can arrow up and down through the dropdown before hitting enter. Does that make this workable enough for now?

**Comment by galenjosephhunter** [comment]
Hi Gabe, clicking still doesn't work for me. I'm going to email you video documentation taken using Chrome that shows you what my user experience is.

**Comment by gsf** [comment]
Thanks for the video -- that's a good way to demonstrate issues you're having. The clicking you specified is working for me as of that commit. Maybe your version of Chrome on OS X treats blur and click events in a different way. I'll see if I can wrangle up a Mac for testing.

**Comment by galenjosephhunter** [comment]
Is this the same issue as #90?
