### ISSUE TITLE
Adding new content from within an associated admin page

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#83]
Will we have the option to add new associated file, like we do in the current site?

If I'm adding a show page, and want to add an associated image, for example, it would be handy to be able to do so via a popup rather than having to add show, save, then add image and attach show separately. If that makes sense?

**Comment by gsf** [comment]
The workflow for your example is to create the image in another tab and link the image on the show page. Does that work for you?

**Comment by galenjosephhunter** [comment]
Absolutely. That would be great.

**Comment by gsf** [comment]
Okay then sounds like #94 is the real issue here, since that should be the workflow presently in place.
