### ISSUE TITLE
Unable to add more than one artist to a broadcast

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#85]
This is related to the difficulty in adding artists, and other related material, but I don't seem to be able to add more than one artist. I'm trying to add a broadcast right now and can (with some difficulty) add an artist, but as soon as I try to add an additional, the first disappears.

**Comment by galenjosephhunter** [comment]
same as #86?

**Comment by gsf** [comment]
Yes, duplicate of #86.
