### ISSUE TITLE
Firefox incompatibilities?

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#93]
Using the Firefox browser in admin to add a broadcast event, the day and time fields are blank.

**Comment by gsf** [comment]
In designing the admin I assumed we could set constraints on browser usage since it's a very small audience. Can we say all users must use Chrome?

**Comment by galenjosephhunter** [comment]
Sure.

On Mon, May 4, 2015 at 12:19 PM, Gabriel Farrell <notifications@github.com>
wrote:

> In designing the admin I assumed we could set constraints on browser usage
> since it's a very small audience. Can we say all users must use Chrome?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavefarm/admin/issues/93#issuecomment-98770859>.
>



-- 
*Galen Joseph-Hunter  /  **Executive Director  /  Wave Farm*
Transmission Arts, WGXC 90.7-FM, Media Arts Grants
5662 Route 23 Acra, NY 12405 518-622-2598 (o) | 917-297-1537 (c)

Subscribe to our email announcements: http://eepurl.com/yRqVP
(Wave Farm is incorporated as free103point9 Inc.)

**Comment by gsf** [comment]
Great. Hope it's not too much trouble. I should have discussed that requirement with you from the start.

**Comment by gsf** [comment]
And we could do an update at some point after launch to make sure it works for Firefox as well -- shouldn't be too much to fix, though this case is a great example, where Firefox doesn't support HTML5 date and time input fields yet.
