### ISSUE TITLE
related items that are linked on one admin page aren't showing as linked on the related item's pages

### ISSUE THREAD

**Issue by galenjosephhunter** [wavefarm/admin#94]
For example, I just added a new image in dev admin. 

I linked, and saved, a related Show on the image's admin page, but the image didn't appear on the Show's public page at dev.wavefarm.org/wgxc/schedule. I went back into admin and looked at the show's admin page. It did not show the image as linked. I added the image to the show page and then it appeared on the public page.

So basically the functionality where items become related regardless of what place that relation was first set isn't happening.

**Comment by gsf** [comment]
This will be fixed when I fix wavefarm/api#57.

**Comment by gsf** [comment]
I believe the functionality is in for wavefarm/api#57. Please test.

**Comment by galenjosephhunter** [comment]
Yes. working! Great.
